[tool.poetry]
name = "course_work"
version = "0.1.0"
description = ""
authors = ["Maxim Zaitsev <eighteenkey@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
